[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/build"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/build/*"
  to = "/index.html"
  status = 200
